<%
'SuperOffice navigation constants
const SUPEROFFICE_PROTOCOL_URL = "superoffice:" 'used to prefix superoffice url's (href, not target)

'Webpanels:
const SUPEROFFICE_PANEL_CONTACT_URL = "contact.main"
const SUPEROFFICE_PANEL_PERSON_URL = "contact.main.person" 
const SUPEROFFICE_PANEL_ASSOCIATE_URL = "contact.main.associate"

'Browser panes: (<a target=..> variables)
const SUPEROFFICE_XIS_MYPAGE_URL = "browserpanel.x-is"
const SUPEROFFICE_XIS_CONSULTANT_URL = "browserpanel.xis-vikar"
const SUPEROFFICE_XIS_TASK_URL = "browserpanel.xis-oppdrag"
const SUPEROFFICE_XIS_ECONOMICS_URL = "browserpanel.xis-økonomi"
const SUPEROFFICE_XIS_REPORTS_URL = "browserpanel.xis-rapporter"
													
'Primary key names
const SUPEROFFICE_CONTACT_ID = "contact_id"
%>